spring:

  datasource:
    url: jdbc:mysql://localhost:3306/clientfy?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        globally_quoted_identifiers: true
        format_sql: true
    open-in-view: false # Melhorar o desempenho ao evitar abrir a sessão além do necessário
  sql:
    init:
      mode: never # Evita a execução de scripts SQL automáticos ao iniciar a aplicação
      continue-on-error: false
